const questions = [
    "A learning process in which a neutral cue comes to trigger a reflex-like reaction after being repeatedly paired with something that naturally produces that reaction. Over time, the cue alone—even without the original trigger—will elicit the same response.",
    "It provides a way to find how one quantity changes at each moment with respect to another, revealing instantaneous growth or decline. This tool determines slopes of curves, predicts motion or trends, and identifies maximum or minimum points in processes. Engineers, scientists, and economists use it to optimize designs, forecast responses to small variations, and model dynamic systems.",
    "A quantum process near the boundary marking where light can’t return creates particle–antiparticle pairs. One partner falls inward, while its counterpart escapes as thermal radiation. The escaping particle carries energy away, so the hole appears to emit heat and slowly loses mass.",
    "Both are large, plant‐eating hoofed mammals native to sub‐Saharan Africa. Each spends much of its day browsing vegetation, has a multi‐chambered stomach to break down tough fibers, and lives in social groups. Both species give birth to single offspring after long pregnancies, rely on strong limbs to support substantial weight, and share evolutionary roots within the even‐toed ungulates.",
    "This nocturnal mammal digs into insect mounds with powerful claws, then probes deep galleries with a long, sticky tongue. Saliva-coated surface clings to countless tiny insects, which are drawn into the mouth with each sweep. A reinforced snout and strong muscles let it break through compact soil quickly. In a rapid feeding burst, it harvests hundreds of these prey items before the tunnel collapses or predators arrive.",
    "Over the last two decades, the unit price climbed from under $3 in 2005 to above $250 by late 2024, driven by breakthroughs like the iPhone and services growth. Brief pullbacks in 2008 and early 2020 reversed quickly. Four-for-one splits in 2014, 2020, and 2022 expanded access. Overall, this ascent delivered roughly a 30% annualized gain—turning a $1,000 stake into about $185,000 by 2023",
]

module.exports = questions;

