name: Sync fork with upstream

on:
  schedule:
    - cron: "15 4 * * *"
  workflow_dispatch:

permissions:
  contents: write

env:
  UPSTREAM_OWNER: AAZZAZRON
  UPSTREAM_REPO: Re-Prompt-That
  # If upstream default branch is not "main", set it here
  UPSTREAM_BRANCH: main
  # Your fork's branch to sync (default branch of this repo)
  TARGET_BRANCH: ${{ github.event.repository.default_branch }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.TARGET_BRANCH }}

      - name: Configure git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          UPSTREAM_URL="https://github.com/${UPSTREAM_OWNER}/${UPSTREAM_REPO}.git"
          git remote add upstream "$UPSTREAM_URL" || git remote set-url upstream "$UPSTREAM_URL"

      - name: Fetch upstream and origin
        run: |
          git fetch --prune origin
          git fetch --prune upstream

      - name: Ensure we are on target branch and up to date with origin
        run: |
          git checkout "${TARGET_BRANCH}"
          git reset --hard "origin/${TARGET_BRANCH}"

      - name: Rebase fork on top of upstream
        run: |
          set -e
          git rebase "upstream/${UPSTREAM_BRANCH}" || {
            echo "::warning::Rebase hit conflicts. Aborting."
            git rebase --abort
            exit 1
          }

      - name: Push updated branch to fork
        run: |
          # Try normal push first
          if ! git push origin "${TARGET_BRANCH}"; then
            echo "::warning::Normal push failed, attempting force-with-lease."
            git push --force-with-lease origin "${TARGET_BRANCH}"
          fi

      - name: Tag run (optional)
        if: always()
        run: echo "Synced with ${UPSTREAM_OWNER}/${UPSTREAM_REPO}@${UPSTREAM_BRANCH}"
