name: Sync fork with upstream

on:
  schedule:
    - cron: "15 4 * * *"
  workflow_dispatch:

permissions:
  contents: write

env:
  # CHANGE THESE TWO to the original repo you forked from
  UPSTREAM_OWNER: AAZZAZRON
  UPSTREAM_REPO: Re-Prompt-That
  # If the upstream default branch is not "main", set it here
  UPSTREAM_BRANCH: main
  # Your fork's branch to sync. Default branch of this repo:
  TARGET_BRANCH: ${{ github.event.repository.default_branch }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.TARGET_BRANCH }}

      - name: Configure git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          # If upstream is private, create a secret named UPSTREAM_TOKEN with repo scope,
          # then uncomment the tokened URL and comment out the https URL.
          # UPSTREAM_URL="https://${UPSTREAM_TOKEN}@github.com/${UPSTREAM_OWNER}/${UPSTREAM_REPO}.git"
          UPSTREAM_URL="https://github.com/${UPSTREAM_OWNER}/${UPSTREAM_REPO}.git"
          git remote add upstream "$UPSTREAM_URL" || git remote set-url upstream "$UPSTREAM_URL"

      - name: Fetch upstream and origin
        run: |
          git fetch --prune origin
          git fetch --prune upstream

      - name: Ensure we are on target branch and up to date with our origin
        run: |
          git checkout "${TARGET_BRANCH}"
          git reset --hard "origin/${TARGET_BRANCH}"

      - name: Rebase fork on top of upstream
        run: |
          set -e
          # This keeps your fork linear on top of upstream
          git rebase "upstream/${UPSTREAM_BRANCH}" || {
            echo "::warning::Rebase hit conflicts. Aborting rebase."
            git rebase --abort
            exit 1
          }

      - name: Push updated branch to fork
        run: |
          # Fast forward most days. If you have local commits, they will be rebased.
          git push origin "${TARGET_BRANCH}"

      - name: Tag run (optional)
        if: always()
        run: echo "Synced with ${UPSTREAM_OWNER}/${UPSTREAM_REPO}@${UPSTREAM_BRANCH}"
